Name:     rhc-playbook-verifier
Version:  1.0.0
Release:  0%{dist}
Summary:  Ansible playbook verifier for Red Hat Insights
License:  MIT

URL:      https://github.com/RedHatInsights/%{name}
# Source0:  %{url}/archive/refs/tags/v%{version}.tar.gz
Source0:  %{name}-%{version}.tar.gz

BuildArch: noarch

BuildRequires: python3-devel
Requires: gpg
%generate_buildrequires
%pyproject_buildrequires

%description
rhc-playbook-verifier package cryptographically verifies Ansible
playbooks generated by Red Hat Insights.

%package -n rhc-playbook-signer
Requires: %{name} = %{version}-%{release}
Summary:  Ansible playbook signer for Ansible playbook verifier

%description -n rhc-playbook-signer
rhc-playbook-signer package cryptographically signs Ansible
playbooks to be used by the verifier.

%prep
%autosetup -p1

%build
%pyproject_wheel

%install
%pyproject_install rhc_playbook_lib rhc_playbook_verifier rhc_playbook_signer
mkdir -p %{buildroot}/%{_libexecdir}
mv %{buildroot}%{_bindir}/%{name} %{buildroot}%{_libexecdir}
mv %{buildroot}%{_bindir}/rhc-playbook-signer %{buildroot}%{_libexecdir}
mkdir -p %{buildroot}/%{_localstatedir}/lib/%{name}/
%pyproject_save_files rhc_playbook_lib rhc_playbook_verifier rhc_playbook_signer

%check
%pyproject_check_import rhc_playbook_lib rhc_playbook_verifier rhc_playbook_signer

%files -n %{name} -f %{pyproject_files}
%{_libexecdir}/%{name}
%attr(700,root,root) %dir %{_localstatedir}/lib/%{name}/
%license LICENSE

%files -n rhc-playbook-signer
%{_libexecdir}/rhc-playbook-signer

%changelog
%autochangelog
